import './globals.css';
import { Inter } from 'next/font/google';
import ReduxProvider from './ReduxProvider';
import UiProvider from './UiProvider';
import Nav from './components/Nav';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Real Estate',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <UiProvider>
            <header>
              <Nav />
            </header>
            <Toaster closeButton />
            <main>{children}</main>
          </UiProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
